Fixes "AttributeError: 'module' object has no attribute 'REDIS_PREFIX'" error when using the Redisd backend.
Caused by the latest change in e9d937b, in constance/backends/redisd.py, line 18.